apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: default
images:
- name: argo-app
  newName: 13612262974/argo-app
  newTag: fa07e31530148eff1f7a71b2a24289bbdfda5312
